### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by chelalv** [Adam-Langley/pybleno#18]
Below is the information:
1. raspberry pi zero w
2. pybleno 0.7
3. lightBlue2.6.4 in ios
when connect,  this connection alert happends often : the peripheral disconnected while being interrogated
below is hcidump log:
> HCI Event: LE Meta Event (0x3e) plen 19
    LE Connection Complete
      status 0x00 handle 64, role slave
      bdaddr 72:39:D6:86:91:F3 (Random)
< HCI Command: LE Read Remote Used Features (0x08|0x0016) plen 2
  0000: 40 00                                             @.
> HCI Event: Command Status (0x0f) plen 4
    LE Read Remote Used Features (0x08|0x0016) status 0x00 ncmd 1
> HCI Event: LE Meta Event (0x3e) plen 12
    LE Read Remote Used Features Complete
      status 0x1a handle 64
      Error: Unsupported Remote Feature / Unsupported LMP Feature
> ACL data: handle 64 flags 0x02 dlen 11
    L2CAP(d): cid 0x003a len 7 [psm 0]
      0000: 09 05 02 00 00 00 00                              .......
> ACL data: handle 64 flags 0x02 dlen 7
    ATT: MTU req (0x02)
      client rx mtu 185
< ACL data: handle 64 flags 0x00 dlen 7
    ATT: MTU resp (0x03)
      server rx mtu 185
> ACL data: handle 64 flags 0x02 dlen 11
    ATT: Read By Group req (0x10)
      start 0x0001, end 0xffff
      type-uuid 0x2800
< ACL data: handle 64 flags 0x00 dlen 24
    ATT: Read By Group resp (0x11)
      attr handle 0x0001, end group handle 0x0005
      value 0x00 0x18
      attr handle 0x0006, end group handle 0x0009
      value 0x01 0x18
      attr handle 0x000a, end group handle 0x000d
      value 0xe0 0xff
> ACL data: handle 64 flags 0x02 dlen 11
    ATT: Read By Group req (0x10)
      start 0x000e, end 0xffff
      type-uuid 0x2800
> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 2
< HCI Command: Disconnect (0x01|0x0006) plen 3
    handle 64 reason 0x13
    Reason: Remote User Terminated Connection
> HCI Event: Command Status (0x0f) plen 4
    Disconnect (0x01|0x0006) status 0x00 ncmd 1
< ACL data: handle 64 flags 0x00 dlen 9
    ATT: Error (0x01)
      Error: Attribute not found (10)
      Read By Group req (0x10) on handle 0x000e
> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 1
> HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 64 reason 0x16
    Reason: Connection Terminated by Local Host
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1
  0000: 01                                                .
> HCI Event: Command Complete (0x0e) plen 4
    LE Set Advertise Enable (0x08|0x000a) ncmd 1
    status 0x00

**Comment by Adam-Langley** [comment]
Hi,
Can you confirm, are you using a Characteristic with the 'indicate' property?
https://github.com/noble/bleno/issues/242

Thanks
