### ISSUE TITLE
Usage of null instead of None

### ISSUE THREAD

**Issue by vinitatgithub** [Adam-Langley/pybleno#23]
In Characteristic.py -> onUnsubscribe method, the values are being set to "null", which causes a crash as null is not defined in python. It should be replaced by "None".

@Adam-Langley I have submitted a pull request as well with the fix.

**Comment by Adam-Langley** [comment]
Hi @vinitatgithub - please create a pull request for your change, then I can review and commit your change - and it will be attributed to you.
There are no permission controls preventing you from doing this.

Let me know how this goes.

**Comment by vinitatgithub** [comment]
Created one and sent it over. Thank you for the quick reply.
