### ISSUE TITLE
IOS LightBlue disconnects immdeiately while interrogating 

### ISSUE THREAD

**Issue by sherifshsffa91** [Adam-Langley/pybleno#26]
Hello Adam , 

while I am trying to test my peripheral using pybleno it connects ok from nrf Connect app but from lightblue it disconnects immediately while interrogating

**Comment by Adam-Langley** [comment]
Hi @sherifshsffa91 - have you met the Bleno prerequisites with regards to disabling bluetoothd?
https://github.com/noble/bleno#prerequisites

**Comment by Adam-Langley** [comment]
If so, this could be tricky to track down. Can you reproduce the issue using any of the Pybleno examples?

**Comment by sherifshsffa91** [comment]
Ok, no I don't follow bleno prerequisites, So let me try it and  I will come back to you to inform you with update

**Comment by sherifshsffa91** [comment]
may the problem in detail was the following :

**Comment by sherifshsffa91** [comment]
may be the problem in detail was :
- once sudo hciconfig hci0 up 
iphone is able to connect only one time 

and then unable to connect again SO I did ,
- every disconnection , killing bluetooth hci thread then deleting stop advertising , then 
- doing 'sudo hciconfig hci0 reset' everytime before bleno.start()

so this solved my issue

**Comment by Adam-Langley** [comment]
Hi @sherifshsffa91 is your platform Pi/Raspbian?
What Raspbian version are you using? Raspbian <= 2008-11-13?

**Comment by sherifshsffa91** [comment]
hello adam 
> Hi @sherifshsffa91 is your platform Pi/Raspbian? yes RPI model 3b+
> What Raspbian version are you using? Raspian 9 (stretch)

**Comment by Adam-Langley** [comment]
Can you tell me exact build?
`uname -a`

**Comment by sherifshsffa91** [comment]
here it is 
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
```

**Comment by Adam-Langley** [comment]
Thanks - ok, you're not subject to the bluetooth bug.
I would suggest, if you want to keep investigating, reproduce the issue and then dump the output dmesg here.
Thanks.
