### ISSUE TITLE
How can i send a string from Pi3 to my iPhone by using pybleno?

### ISSUE THREAD

**Issue by tanakitti** [Adam-Langley/pybleno#41]
I am working on my project that reading some data from Pi3's sensors and send them to my iPhone as a string. I have followed your echo tutorial and it worked very well but I don't to how to send some data back to BLE terminal.

Ps. I think that if I can send data back to my phone, it will be a good starting point of my project.

Thank you for all of your answers

**Comment by Adam-Langley** [comment]
Hi @tanakitti  - please try a forum like stackoverflow.com - this is reserved for issue reports only.
