### ISSUE TITLE
Is there a way to a force a certain MTU?

### ISSUE THREAD

**Issue by izi01** [Adam-Langley/pybleno#54]
Hi, 
I don't know if this is the right place, but I would greatly appreciate a little guidance. 

I am trying to create an application that consists of several GATT services, and works together with a smartphone app that I can not change. 

This app expects a MTU of 120 bytes but never negotiates this with my application. So the `ATT_OP_MTU_REQ` is never received and `Gatt.handleMtuRequest` is never called. 

Therefore my application thinks the MTU is 23 (default)  and when I try to notify on a characteristic with a value longer than 23 bytes the value is truncated and only partly received by the app. 

So I know it is the app's fault, but I can't do anything about it apart from setting the MTU manually. But I was not able to manage that. 
I tried calling `bleno.onMtuChange(120)`. this trigger the `mtuChange` callback, but the `updateValueCallback` that my characteristic receives during `onSubscribe` still only accepts 20 bytes (23=mtu, minus 3 bytes).

Is there any other way to force a MTU of 120 bytes?

**Comment by Adam-Langley** [comment]
Hi izi01,

unfortunately the goal of this project is simply a port of Bleno from Node to Python - you will need to direct your type of queries to the author of Bleno (Sandeep Mistry), and his suggestions should closely translate to Pybleno also.

If, however, you find that Pybleno has a bug which differs from Bleno - that is something that can be registered as an issue.

**Comment by izi01** [comment]
ok, thanks for the answer.
